# Assignment 1 : NumPy

In [2]:
import numpy as np

In [7]:
#Create a null vector of size 10 but the fifth value which is 1

x = np.zeros(10).astype(int)
x[4] = 1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [9]:
# Create a vector with values ranging from 10 to 49

x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
#Create a 3x3 matrix with values ranging from 0 to 8

mat1 = np.random.randint(0, 8, (3,3))
mat1

array([[0, 7, 3],
       [2, 6, 1],
       [2, 3, 5]])

In [15]:
# Find indices of non-zero elements from [1,2,0,0,4,0]

mat2 = np.array([1,2,0,0,4,0])
mat2.nonzero()

array([1, 2, 4])

In [16]:
#Create a 10x10 array with random values and find the minimum and maximum values.

b= np.random.randint(100, size = (10,10))
print('Minimum value in b =', b.min())
print('Minimum value in b =', b.max())

Minimum value in b = 2
Minimum value in b = 99


In [19]:
#Create a random vector of size 30 and find the mean value.

mat = np.random.randint(30)
print ('Overall mean of matrix is \n%s\n'%np.mean(mat))

5